image: "hseeberger/scala-sbt"

variables:
  SBT_OPTS: "-Dsbt.global.base=/sbt-cache/.sbtboot -Dsbt.boot.directory=/sbt-cache/.boot -Dsbt.ivy.home=/sbt-cache/.ivy"

stages:
  - publish
  - pages

allinone:
  stage: publish
  script:
    - sbt clean test publish

pages:
  stage: pages
  script:
    - sbt clean coverage test coverageReport coverageOff doc
    - cp -r target/scala-2.12/scoverage-report public/scoverage-report
    - cp -r target/scala-2.12/api public/api
  artifacts:
      paths:
        - public