image: "hseeberger/scala-sbt"

# disable gitlab cache (the directory /cache is mapped to a physical directory on the server)
#cache:
#  key: "$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
#  untracked: true
#  paths:
#    - "/cache/.ivy"
#    - "/cache/.boot"
#    - "/cache/.sbtboot"
#    - "/cache/target"

variables:
  SBT_OPTS: "-Dsbt.global.base=/sbt-cache/.sbtboot -Dsbt.boot.directory=/sbt-cache/.boot -Dsbt.ivy.home=/sbt-cache/.ivy"

stages:
  - test
  - doc
  - publish
  - pages

test:
  stage: test
  script:
    - sbt clean coverage test coverageReport
    - cp target/scala-2.11/scoverage-report/index.html public/coverage.html

doc:
  stage: doc
  script:
    - sbt clean doc
    - cp target/scala-2.11/api public/api

publish:
  stage: publish
  script:
    - sbt clean publish

pages:
  stage: pages
  script:
    - echo "Nothing to do here..."
  artifacts:
    paths:
      - public
  only:
    - master